# Create a list of all the fields in the full version of the NHSPD download.
# Field names taken from Annex A of the User Guide inside the NHSPD zip file.

nhspd_full_fields = [
    "postcode",
    "postcode_egif",
    "date_start",
    "date_end",
    "ng_east_100m",
    "ng_north_100m",
    "la_organisation",
    "la_district",
    "ward",
    "user_type",
    "ng_quality",
    "country",
    "former_ha",
    "region",
    "pre2002_ha",
    "nhser",
    "sub_icb",
    "null_1",
    "null_2",
    "null_3",
    "null_4",
    "oa_2001",
    "nhsrlo",
    "former_sha",
    "lsoa_2001",
    "null_5",
    "null_6",
    "former_cn",
    "nhsscn",
    "first_sha",
    "first_pct",
    "itc",
    "constituency",
    "cancer_registry",
    "second_pct",
    "ngr_east_1m",
    "ngr_north_1m",
    "oa_2011",
    "lsoa_2011",
    "msoa_2011",
    "cal",
    "icb",
    "smhpc_eating",
    "smhpc_secure",
    "smhpc_child",
    "oa_2021",
    "lsoa_2021",
    "msoa_2021"
]

print(nhspd_full_fields)
