# ------------------------------------
# SITE SETTINGS
# ------------------------------------
title: nhstech.uk
description: A project looking at the use of tech in UK health and care

# ------------------------------------
# GITHUB PAGES/JEKYLL CONFIGURATION
# ------------------------------------

github_repo_url: "https://github.com/regulate-tech/nhstech" 
github_repo: regulate-tech/nhstech

# BASEURL: Must match the repository name for Project Pages
# This ensures that internal links start with /nhstech/
baseurl: "/nhstech"

# URL: This is the host URL. Use your actual GitHub username/organization.
url: "https://regulate-tech.github.io"

# URL settings for GitHub Pages live
# baseurl: ""  # Empty for custom domain
# url: "https://nhstech.uk"

# THEME: Use a theme supported by GitHub Pages
theme: minima

# ------------------------------------
# JEKYLL BUILD SETTINGS (For Local Testing)
# ------------------------------------
# Exclude the vendor folder where local gems are installed
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

# Set simple links for posts
permalink: /:title/

# Navigation Links
header_pages:
  - code.md
  - data.md
  - policy.md
  - posts.md

author:
  name: Richard Allan
  
github_username: regulate-tech

# Hide GitHub repository information
github_username: # leave blank
repository: # leave blank
show_downloads: false
github:
  is_project_page: false
  is_user_page: false

# Disable repository link
public: false