# ------------------------------------
# GITHUB PAGES/JEKYLL CONFIGURATION
# ------------------------------------

# URL settings for GitHub Pages live
# Comment out one for main or staging branches
baseurl: ""  # Empty for custom domain
url: "https://nhstech.uk"

# URL settings for GitHub Pages live
# baseurl: ""  # Empty for custom domain
# url: "https://staging.nhstech.uk"